name: novels
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
    sdk: ^3.13.1

dependencies:
    hive: ^2.2.3
    hive_flutter: ^1.1.0
    flutter_slidable: ^4.0.3
    permission_handler: 11.3.1
    expandable_text: 2.3.0

    flutter:
        sdk: flutter
    cupertino_icons: ^1.0.8

dev_dependencies:
    flutter_test:
        sdk: flutter
    hive_generator: ^2.0.1
    build_runner: ^2.4.6

    flutter_launcher_icons: ^0.14.4

    flutter_lints: ^6.0.0
    change_app_package_name: ^1.5.0

flutter:
    uses-material-design: true

    assets:
        - assets/fonts/JetBrainsMonoNLNerdFontMono-Regular.ttf
        - assets/data.json

        - assets/nvls/assassinate_wonderwind/
        - assets/nvls/deep_sea_embers/
        - assets/nvls/super_minion/
        - assets/nvls/bloodstone_immortal_five_element_sovereign/
        - assets/nvls/clara_casewell,_attorney_to_the_villainess/
        - assets/nvls/ending_maker/
        - assets/nvls/i_am_the_heroine's_master/
        - assets/nvls/i_became_the_scoundrel_in_the_popular_dating_sim/
        - assets/nvls/i_only_love_my_greatest_enemy/
        - assets/nvls/kidnapped_dragons/
        - assets/nvls/leaving_a_legacy/
        - assets/nvls/magical_girl_gunslinger/
        - assets/nvls/max_level_sword_sage/
        - assets/nvls/mother_of_learning/
        - assets/nvls/my_glorius_life/
        - assets/nvls/others_summon_dragons_i_summon_legendary_knights/
        - assets/nvls/reverend_insanity/
        - assets/nvls/rock_falls,_everyone_dies/
        - assets/nvls/shadow_slave/
        - assets/nvls/supreme_magus/
        - assets/nvls/the_author's_pov/
        - assets/nvls/the_dungeon_of_arceus/
        - assets/nvls/the_perfect_run/
        - assets/nvls/the_second_coming_of_gluttony/
        - assets/nvls/the_world_of_otome_games_is_tough_for_mobs/
        - assets/nvls/the_worst_litrpg_story_on_royal_road/
        - assets/nvls/throne_of_time/

    fonts:
        - family: JetBrainsMono
          fonts:
              - asset: assets/fonts/JetBrainsMonoNLNerdFontMono-Regular.ttf

flutter_launcher_icons:
    android: true
    ios: false
    image_path: "assets/icon/theicon.png"
    min_sdk_android: 21
